#!/bin/bash --login
###
#SBATCH --job-name=16_10
#SBATCH --output=bench.out.%J
#SBATCH --error=bench.err.%J
#SBATCH --time=15
#SBATCH --ntasks=160
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=16
###
#now run normal batch commands 
module purge
module load intel
module load mvapich2/2.2rc2
mpirun ./BGK CNT_Sim_Demo.con &> output
