          SUBROUTINE COMPMU(rv,VNPNT,NPOIN,NNODE,&
     &          DISNF,VCORD,INTMA,NELEM,GEOME,NGEOM,&
     &          MU,UX,UY,DISND,DISUX,DISUY,RANK,SUMWEIGHT,d)
!
! *** THIS SUBROUTINE COMPUTES THE MU VALUE REQUIRED TO CONSTRUCT THE BGK RHS
!
        IMPLICIT NONE
!
        INTEGER VNPNT,NPOIN,NNODE,NELEM,NGEOM,IE,IP,IV,IN,IVT
        INTEGER INTMA(NNODE,NELEM),RANK
	REAL rv,d,PI,CO,ETA,ZETA,RT,THETA,CX,CY,WEIGHT,JAC,SUMWEIGHT,C1,C2
        REAL FRAC,CT,C4,DISUX(NNODE,NELEM),DISUY(NNODE,NELEM),CR,UX,UY 
        REAL CX0,CY0,CDASH,SIGT,INTMU,SUMMUV,MUV(VNPNT),VCORD(3,VNPNT) 
        REAL GEOME(NGEOM,NELEM),DISND(NNODE,NELEM),ND 
        REAL MU(NNODE,NELEM),DISNF(NNODE,VNPNT,NELEM)

!  ! *** PARAMETERS !
        PARAMETER(PI=3.1416,C4=4.0)
!
! *** CALCULATE THE SCALING FRACTIN FOR V-SPACE INTEGRATION
!
        FRAC=C4/SUMWEIGHT
!
! *** INITIALISE THE MU ARRAY
!
        CO=0.0
        CALL RFILLM(MU,NNODE,NELEM,CO)
!
! *** CALCULATE THE TOTAL COLLISION CROSS SECTION FOR AN OXYGEN MOLECULE
!
        SIGT=PI*d*d
!
! *** LOOP OVER EACH DISCONTINUOUS NODE IN P-SPACE
!
        DO 1000 IE=1,NELEM
        DO 1001 IN=1,NNODE
!
! *** NUMBER DENSITY AT THIS NODE
!
        ND=DISND(IN,IE)
        IF(ND.LT.1e-20)GOTO 1004
!
! *** BULK VELOCITY COMPONENTS
!
        CX0=DISUX(IN,IE)
        CY0=DISUY(IN,IE)
!
! *** LOOP OVER ALL V-SPACE POINTS TO DETERMINE THE MEAN THERMAL VELOCITY
!
        CT=0.0
        DO 1003 IV=1,VNPNT 
        ETA=VCORD(1,IV)
        ZETA=VCORD(2,IV)
        RT=(rv/2)*(ETA+1)
        THETA=ZETA*PI
        CX=RT*COS(THETA)
        CY=RT*SIN(THETA)
        WEIGHT=VCORD(3,IV)
        JAC=PI*rv*rv*0.25*(ETA+1)     !JACOBIAN OF THE TRANSFORMATION
        C1=(CX0-CX)*(CX0-CX)+(CY0-CY)*(CY0-CY)
        CDASH=SQRT(C1)     !RELATIVE VELOCITY
        CT=CT+CDASH*(DISNF(IN,IV,IE)/ND)*WEIGHT*JAC*FRAC
 1003 CONTINUE
 1004 CONTINUE
!
! *** NOW CALCULATE THE MEAN COLLISION FREQUENCY
!
        C2=2.0
        CR=SQRT(C2)*CT
        MU(IN,IE)=CR*SIGT*DISND(IN,IE)
!
! *** END LOOP OVER THE DISCONTINUOUS NODES
!
 1001 CONTINUE
 1000 CONTINUE
!
! *** RETURN TO ADVNCE
!
        RETURN
        END
