       SUBROUTINE FLUCON2(NELEM,VNPNT,DISNF,NBNOI,NBOUN,& 
     &                  BSIDO,NBNOR,RSIDO,VCORD,rv,& 
     &                 ETA,NSIDE,ISIDE,RANK,RORDER,TORDER,SUMWEIGHT&
     &                 ,R) 
! 
! *** THIS SUBROUTINE CALCULATE THE MASS CONSERVATION PARAMETER (ETA) AT 
! *** EACH BOUNDARY NODE FOR USE IN GETBOU.f WHEN CALCULATING THE FLUX OF 
! *** MOLECULES THAT HAVE BOUNCED OFF THE WALL 
!
      IMPLICIT NONE
      include 'mpif.h' 
! 
      INTEGER NELEM,VNPNT,NBNOI,NBOUN,IP1,IP2 
      INTEGER NBNOR,IB,IV,IS,RANK,IV1,IV2,IETA,IZETA 
      INTEGER NSIDE,RORDER,TORDER,IV3,IV4
      INTEGER BSIDO(NBNOI,NBOUN),IEL,ISIDE(8,NSIDE) 
      INTEGER IN1,IN2,IP1T,IP2T,MPI_IERR,ITYPE 
      REAL RSIDO(NBNOR,NBOUN),ETA1,ZETA1,RT,THETA,THETA2 
      REAL VCORD(3,VNPNT) 
      REAL rv,ANX,ANY,TEST,VNORM,DIFF1,DIFF2,DIFF3,DIFF4 
      REAL CX,CY,PI,JAC,WEIGHT,SUMWEIGHT,FRAC 
      REAL TEMP,Mw,nf,ETATEST1,ETATEST2,ZETATEST1,ZETATEST2
      REAL nf1,nf2,THETA1,ETAf,ZETAf,nf11,nf12 
      REAL SPEED,R,C1,C2,C3,C4,Co4
      REAL DISNF(3,VNPNT,NELEM),SUMTOP,SUMBOTTOM,ETA(NBOUN)
      REAL CX1,CX2,CX3,CX4,CY1,CY2,CY3,CY4
      CHARACTER filename*80
! 
! *** SET UP GAS CONSTANT AS A PARAMETER 
! 
      PARAMETER(PI=3.1416,Co4=4.0)
      FRAC=Co4/SUMWEIGHT
! 
! *** LOOP OVER THE BOUNDARY SIDES 
!
      DO 100 IB=1, NBOUN
      IP1=BSIDO(1,IB) 
      IP2=BSIDO(2,IB) 
      IEL=BSIDO(3,IB)
      ITYPE=BSIDO(4,IB)
      IF(ITYPE.EQ.4)THEN 
      ANX=RSIDO(1,IB) 
      ANY=RSIDO(2,IB) 
      TEMP=BSIDO(5,IB)
      IF((ANX.GT.0).AND.(ANY.GE.0))THEN
      THETA1=ATAN(ANY/ANX)-(PI/2)
      ELSEIF((ANX.LE.0).AND.(ANY.GT.0))THEN
      IF(ANX.EQ.0.0)THEN
      THETA1=PI/2
      GOTO 159
      ENDIF
      THETA1=(PI/2)-ATAN(ABS(ANY/ANX))
      ELSEIF((ANX.LT.0).AND.(ANY.LE.0))THEN
      THETA1=ATAN(ABS(ANY/ANX))+(PI/2)
      ELSEIF((ANX.GE.0).AND.(ANY.LT.0))THEN
      IF(ANX.EQ.0)THEN
      THETA1=-PI/2
      GOTO 159
      ENDIF  
      THETA1=-ATAN(ABS(ANY/ANX))-(PI/2)
      ENDIF
 159  CONTINUE
!
! *** COMPUTE THETA2
!
      THETA2=THETA1+PI        !WE WILL THEN INTEGRATE BETWEEN THESE TWO ANGLES
      IF(THETA2.GT.(PI+0.01))THETA2=THETA2-2*PI
! 
! *** FIND BOUNDARY SIDE EDGE IN ISIDE TO GET LOCAL NODE NUMBERS 
! 
      DO 400 IS=1,NSIDE 
      IP1T=ISIDE(1,IS) 
      IP2T=ISIDE(2,IS) 
      IF((IP1.EQ.IP1T).AND.(IP2.EQ.IP2T))THEN 
      IN1=ISIDE(5,IS) 
      IN2=ISIDE(6,IS) 
      GOTO 401 
      ELSEIF((IP2.EQ.IP1T).AND.(IP1.EQ.IP2T))THEN 
      IN1=ISIDE(6,IS) 
      IN2=ISIDE(5,IS) 
      GOTO 401 
      ENDIF 
 400  CONTINUE 
 401  CONTINUE
! 
! *** LOOP OVER ALL VELOCITY SPACE NODES IN THE TRANSFORMED HEMISPHERE THAT 
! *** BEGINS AT THETA1
! 
        SUMTOP=0.0
       DO 200 IV=1,VNPNT 
       ETA1=VCORD(1,IV)                
       ZETA1=VCORD(2,IV)              
       RT=ETA1*(rv/2)+(rv/2)       !MAP BACK TO POLAR COORDINATES 
       THETA=ZETA1*PI
       IF(ANX.GE.0)THEN
       IF((THETA.GE.THETA1).AND.(THETA.LE.THETA2))THEN
       CX=RT*COS(THETA)            !CONVERT TO CARTESIANS 
       CY=RT*SIN(THETA)
! 
! *** IS THE FLUX INTO OR AWAY FROM THE WALL? 
! 
      TEST=CX*ANX+CY*ANY
      VNORM=ABS(TEST) 
      JAC=PI*rv*rv*0.25*(ETA1+1) 
      WEIGHT=VCORD(3,IV)
        nf1=DISNF(IN1,IV,IEL)
        nf2=DISNF(IN2,IV,IEL)
        nf=0.5*(nf1+nf2)
!
        SUMTOP=SUMTOP+VNORM*nf*JAC*WEIGHT*FRAC
        ELSE
        CONTINUE
        ENDIF 
!
        ELSEIF(ANX.LE.0)THEN
!
       IF((THETA.GE.THETA1).OR.(THETA.LE.THETA2))THEN
       CX=RT*COS(THETA)            !CONVERT TO CARTESIANS 
       CY=RT*SIN(THETA)
! 
! *** IS THE FLUX INTO OR AWAY FROM THE WALL? 
! 
      TEST=CX*ANX+CY*ANY
      VNORM=ABS(TEST) 
      JAC=PI*rv*rv*0.25*(ETA1+1) 
      WEIGHT=VCORD(3,IV)
        nf1=DISNF(IN1,IV,IEL)
        nf2=DISNF(IN2,IV,IEL)
        nf=0.5*(nf1+nf2)
!
        SUMTOP=SUMTOP+VNORM*nf*JAC*WEIGHT*FRAC
        ELSE
        CONTINUE
        ENDIF 
!
        ENDIF       
! *** END THE LOOP OVER VELOCITY SPACE 
! 
 200  CONTINUE
! *** USE AN ANALYTICAL DERIVATION FOR THE DENOMINATOR
       SUMBOTTOM=SQRT(2*PI*(R**3)*(REAL(TEMP))**3)
! 
! *** CALCULATE ETA 
! 
      IF(SUMBOTTOM.LT.0.1)THEN 
      WRITE(*,500) 
      WRITE(*,501) 
      STOP 
      ENDIF
!	
       ETA(IB)=SUMTOP/SUMBOTTOM
!       ETA(IB)=5.1609237e19
!
      ELSE
      ETA(IB)=0.0
      ENDIF
! 
! *** END LOOP OVER THE BOUNDARY SIDES 
! 
 100  CONTINUE
! 
! *** FORMAT STATEMENTS 
! 
  500 FORMAT('ERROR CALCULATING FLUX CONSERVATION PARAMETER IN FLUCON') 
  501 FORMAT('PROGRAM STOPPED!') 
     RETURN 
      END 
         
 
         
       
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
       
