      SUBROUTINE GETFLA(NELEM,NNODE,VNPNT,DISNF,FLUXX,& 
     &               FLUYY,UX,UY,IV) 
! 
      INTEGER NNODE,VNPNT,NELEM,IV 
      REAL DISNF(NNODE,VNPNT,NELEM) 
      REAL FLUXX(1,3,NELEM),FLUYY(1,3,NELEM) 
      REAL UX,UY,CO 
! *** INITIALISE FLUXX AND FLUYY 
      CO=0.0 
      CALL RFILLA(FLUXX,1,3,NELEM,CO) 
      CALL RFILLA(FLUYY,1,3,NELEM,CO) 
! *** GET THE FLUXES 
        DO 1001 IE=1,NELEM 
        DO 1000 IN=1,3 
! *** DEAL WITH THE CASE OF A VACCUUM (WHEN DISNF IS VERY, VERY SMALL!) 
        TMP=ABS(DISNF(IN,IV,IE)) 
        IF(TMP.EQ.0.0)THEN 
          FLUXX(1,IN,IE)=0.0 
          FLUYY(1,IN,IE)=0.0 
          GOTO 2000 
          ENDIF 
! *** OTHERWISE UNDER NORMAL CIRCUMSTANCES 
      FLUXX(1,IN,IE)=UX*DISNF(IN,IV,IE) 
      FLUYY(1,IN,IE)=UY*DISNF(IN,IV,IE) 
 2000 CONTINUE 
 1000 CONTINUE 
 1001 CONTINUE 
! 
      RETURN 
      END 
