       SUBROUTINE GETRES(IV,VNPNT,RESIDUAL,RESIDUAL_PP,RANK,NPROC) 
! 
! *** THIS SUBROUTINE COLLECTS IN THE RESIDUALS FROM ALL THE PROCS AND FINDS THE LARGEST 
! 
      IMPLICIT NONE 
      INCLUDE 'mpif.h' 
! 
       INTEGER RANK,NPROC,IPR,MPI_IERR,MPI_STATUS(MPI_STATUS_SIZE)
       INTEGER IV,VNPNT 
       REAL RESIDUAL_PP,RESIDUAL(VNPNT),RESIDUALnew 
! 
      IF(RANK.EQ.0)THEN 
         RESIDUAL(IV)=0.0 
      ENDIF 
      DO 1000 IPR=1,NPROC-1 
           IF(RANK.EQ.IPR)THEN
             CALL MPI_SEND(RESIDUAL_PP,1,MPI_REAL,0,1,& 
     &       MPI_COMM_WORLD,MPI_IERR) 
         ENDIF 
           IF(RANK.EQ.0)THEN 
             CALL MPI_RECV(RESIDUALnew,1,MPI_REAL,IPR,1,&
     &       MPI_COMM_WORLD,MPI_STATUS,MPI_IERR) 
           IF(RESIDUALnew.GT.RESIDUAL(IV))THEN 
                RESIDUAL(IV)=RESIDUALnew 
                ENDIF 
           ENDIF 
 1000 CONTINUE 
! 
      RETURN 
      END 
                 
             
