        SUBROUTINE GTEQNF(NFO,NNODE,NELEM,DISND,DISUX,DISUY,DISPS,&
     &           VNPNT,VCORD,UX,UY,RANK,M)
!
! *** THIS SUBROUTINE CALCULATES THE EQUILIBRIUM NF BASED ON THE DISCONTINUOUS
! *** BULK FLOW CONDITIONS FOR USE IN CALCULATING THE BGK RHS
!
        IMPLICIT NONE
!
        INTEGER NNODE,NELEM,VNPNT,IE,IN,RANK
!
	REAL PI,M,BETA2,PS,UX,UY,ND,TMP,CX,CY,NA,MM,RHO
	REAL NFO(NNODE,NELEM),DISND(NNODE,NELEM),DISUX(NNODE,NELEM)
	REAL DISUY(NNODE,NELEM),DISPS(NNODE,NELEM),VCORD(3,VNPNT)
!
! *** PARAMETERS
!
        PARAMETER(PI=3.1416,NA=6.022e26)
!
! *** INITIALISE
!
        CALL RFILLM(NFO,NNODE,NELEM,0.0)
!
! *** LOOP OVER ALL THE DISCONTINUOUS P-SPACE NODES
!
        DO 1000 IE=1,NELEM
        DO 1001 IN=1,NNODE
        ND=DISND(IN,IE)    !NUMBER DENSITY
        MM=M/NA
        RHO=MM*ND
        PS=DISPS(IN,IE)  !BULK STATIC PRESSURE
        IF(PS.LT.1e-20)GOTO 1003
        CX=DISUX(IN,IE)   !BULK VELOCITIES
        CY=DISUY(IN,IE)
        BETA2=RHO/(2*PS)     !BETA SQUARED
!IF((RANK.EQ.3).AND.(IE.EQ.665).AND.(IN.EQ.1))THEN
!PRINT*,'BETA2=',BETA2,'RHO=',RHO,'PS=',PS
!ENDIF
        TMP=-BETA2*((CX-UX)*(CX-UX)+(CY-UY)*(CY-UY))
        NFO(IN,IE)=ND*(BETA2/PI)*EXP(TMP)
 1003 CONTINUE
 1001 CONTINUE
 1000 CONTINUE
!
! *** RETURN TO ADVNCE
!
        RETURN
        END

