      SUBROUTINE ADTHEM(IV,VNPNT,DISNF,DELUN,NELEM,&
     &       VSPACE_FIRST,VSPACE_LAST)
) 
! 
      INTEGER NELEM,IV,VNPNT 
      REAL DELUN(1,3,NELEM) 
      REAL MAXnf(VNPNT),TEST,COMP 
      INTEGER VSPACE_FIRST,VSPACE_LAST
      REAL DISNF(3,VSPACE_FIRST:VSPACE_LAST,NELEM_PP) 

! 
! *** ADDING THE INCREMENTS 
! 
      DO 1000 IE=1,NELEM 
      DO 2000 IN=1,3 
      DISNF(IN,IV,IE)=DISNF(IN,IV,IE)+DELUN(1,IN,IE) 
!
! *** CHECK TO ENSURE THAT nf DOES NOT GO NEGATIVE
!
      IF(DISNF(IN,IV,IE).LT.0.0)DISNF(IN,IV,IE)=0.0
!
 2000 CONTINUE 
 1000 CONTINUE 
! 
       RETURN 
       END 
