MODULE ADTHEM_MODULE
CONTAINS

  SUBROUTINE ADTHEM(IV, DISNF, DELUN, NELEM_PP,&
       &       VSPACE_FIRST, VSPACE_LAST)
!
    IMPLICIT NONE
    INTEGER NELEM_PP, IV
    REAL DELUN(1, 3, NELEM_PP)
    INTEGER VSPACE_FIRST, VSPACE_LAST
    REAL DISNF(3, VSPACE_FIRST:VSPACE_LAST, NELEM_PP)
    INTEGER IE, IN

!
! *** ADDING THE INCREMENTS
!
    DO IE = 1, NELEM_PP
    DO IN = 1, 3
      DISNF(IN, IV, IE) = DISNF(IN, IV, IE) + DELUN(1, IN, IE)
!
! *** CHECK TO ENSURE THAT nf DOES NOT GO NEGATIVE
!
      IF (DISNF(IN, IV, IE) .LT. 0.0) DISNF(IN, IV, IE) = 0.0
!
    ENDDO
    ENDDO
!
    RETURN
  END
END MODULE ADTHEM_MODULE
