SUBROUTINE GETLEN(NNODE, NELEM, RELEN, NGEOM, GEOME)
!
  IMPLICIT NONE

  INTEGER :: NNODE,NELEM,NGEOM

  REAL GEOME(NGEOM, NELEM)
  REAL RELEN(NELEM), DIST(3)

  REAL :: ANX, ANY, C10
  INTEGER :: IE, IN, IK
!
! *** COMPUTE THE ELEMENT LENGTHS
!
  C10 = 1.0
!
  DO IE = 1, NELEM
    DIST = -1.0
    DO IN = 1, NNODE
      ANX = GEOME(IN, IE)
      IK = IN + NNODE
      ANY = GEOME(IK, IE)
      DIST(IN) = C10/SQRT(ANX*ANX + ANY*ANY)
    ENDDO
    RELEN(IE) = MIN(DIST(1), DIST(2), DIST(3))
  ENDDO
!
  RETURN
END
