MODULE GETRES_MODULE
CONTAINS
  SUBROUTINE GETRES(RESIDUAL, RESIDUAL_PP, &
                    MPI_RANK_P, VSPACE_FIRST, &
                    VSPACE_LAST, MPI_COMM_P)
!
! *** THIS SUBROUTINE COLLECTS IN THE RESIDUALS FROM ALL THE PROCS AND FINDS THE LARGEST
!
    IMPLICIT NONE
    INCLUDE 'mpif.h'
!
    INTEGER MPI_RANK_P, MPI_COMM_P, VSPACE_FIRST, VSPACE_LAST
    INTEGER MPI_IERR
    INTEGER IV
    REAL RESIDUAL(VSPACE_FIRST:VSPACE_LAST)
    REAL RESIDUAL_PP(VSPACE_FIRST:VSPACE_LAST)
!

    IF (MPI_RANK_P .EQ. 0) THEN
      DO IV = VSPACE_FIRST, VSPACE_LAST
        RESIDUAL_PP(IV) = 0.0
      ENDDO
    ENDIF
    CALL MPI_REDUCE(RESIDUAL_PP(VSPACE_FIRST:VSPACE_LAST), &
                    RESIDUAL(VSPACE_FIRST:VSPACE_LAST), &
                    VSPACE_LAST + 1 - VSPACE_FIRST, &
                    MPI_REAL, MPI_MAX, 0, MPI_COMM_P, MPI_IERR)

    RETURN
  END

END MODULE GETRES_MODULE
