       SUBROUTINE INICON(NPOIN,NNODE,NELEM,NELEM_PP,INTMA_PP,ELGRP,& 
     &     NPOIN_PP,COORD_PP,VNPNT,VCORD,DISNF_PP,IPCOM_PP,RANK,rv,IVD) 
! 
! *** THIS SUBROUTINE ESTABLISHES THE INITIAL CONDITIONS OF THE PROBLEM 
! 
       IMPLICIT NONE 
      INCLUDE 'mpif.h' 
      TYPE InputVariables
          INTEGER :: TORDER !Quadrature order in Theta for V-SPACE
          INTEGER :: NTIME !Number of timesteps
          INTEGER :: IMMAT !Lumped mass matrices (no/yes)
          INTEGER :: RS !Using Restart data (no/yes)
          INTEGER :: INF !Is there an inflow (no/yes)
          REAL :: CSAFM !Safety factor applied to timestep (Courant)
          REAL :: rv !Radial extent of the V-SPACE
          REAL :: T1 !Initial condition temp
          REAL :: P1 !Initial condition pressure
          REAL :: U0 !Initial condition X-vel
          REAL :: V0 !Initial condition Y-vel
          REAL :: CINF(4)
          REAL :: W
          REAL :: ALPHA
      END TYPE

! *** DECLARE VARIABLES 
! 
      TYPE(InputVariables) :: IVD
      INTEGER IN,INV,RS,IV,IP,NELEM,NPOIN,NNODE,RANK,maxNELEM_PP 
      INTEGER IE,TAG,IP_PP,I,IE_PP,NELEM_PP 
      INTEGER VNPNT,NPOIN_pp,IPT,INTMA_PP(NNODE,NELEM_PP) 
      INTEGER TEST1,TEST2,NRANK,IPCOM_PP(NPOIN_PP) 
      INTEGER ELGRP(NELEM,2),MPI_IERR,MPI_STATUS 
! 
      REAL VCORD(3,VNPNT),COORD_PP(2,NPOIN_PP) 
      REAL T1,P1,GC,RHO1,n1,NA,C0,ETA,ZETA,R,THETA 
      REAL M,BETA1,TMP1,MAGX,rv,C 
      REAL UX,UY,TMP,SPEED,CO,PI,F0,XPOS 
      REAL SUM,W,L 
      REAL DISNF_PP(NNODE,VNPNT,NELEM_PP),DISNFPARCEL(NNODE) 
! 
      CHARACTER filename*80,TEXT*80 
! 
! *** SET PI, GAS CONSTANT (GC),MOLAR MASS AND AVAGADRO'S NUMBER AS PARAMETERS 
! 
      PARAMETER(GC=0.287E+03,NA=6.022E+026,M=29,PI=3.1416)
! 
! *** INITIALISE INCON 
! 
      C0=0.0
      IF(RANK.NE.0)THEN 
       CALL RFILLA(DISNF_PP,NNODE,VNPNT,NELEM_PP,C0)
      ENDIF
! 
! *** ASK THE USER IF THEY ARE USING A RESTART FILE AS INITIAL CONDITIONS 
! 
      IF(RANK.EQ.0)THEN 
      WRITE(*,*) 
      RS = IVD%RS 
      ENDIF     !LINKS WITH IF STATEMENT ON LINE 41 
      CALL MPI_BCAST(RS,1,MPI_INTEGER,0,MPI_COMM_WORLD,MPI_IERR)
! 
! *** IF USING A RESTART FILE ASK FOR THE NAME OF THE FILE 
! 
      IF(RS.EQ.1)THEN 
      IF(RANK.EQ.0)THEN 
151   READ(21,*) filename 
      OPEN  (11, file=filename, status='old', err=151) 
      WRITE(*,*) 'READING RESTART FILE =',filename 
      WRITE(*,*) 
! 
! *** READ IN DATA FROM RESTRT FILE 
! 
      READ(11,*) TEXT 
      READ(11,*) TEST1,TEST2 
! 
! *** CHECK DATA 
! 
      IF((TEST1.NE.NPOIN).OR.(TEST2.NE.VNPNT))THEN 
      WRITE(*,208) 
      WRITE(*,209) 
      STOP 
      ENDIF 
! 
      ENDIF    !LINKS WITH IF STATEMENT ON LINE 45
! 
! *** READ DISNF_PP 
! 
      DO 1010 IV=1,VNPNT 
      DO 1011 IE=1,NELEM 
        IF(RANK.EQ.0)THEN 
            READ(11,*) (DISNFPARCEL(I),I=1,NNODE) 
! *** CHECK THE SLAVE ALLOCATION OF THIS ELEMENT 
            NRANK=ELGRP(IE,1) 
                IE_PP=ELGRP(IE,2) 
            ENDIF     !LINKS WITH IF STATEMENT ON LINE 73 
! *** BROADCAST 
                CALL MPI_BCAST(NRANK,1,MPI_INTEGER,0,& 
     &            MPI_COMM_WORLD,MPI_IERR) 
                CALL MPI_BCAST(IE_PP,1,MPI_INTEGER,0,& 
     &            MPI_COMM_WORLD,MPI_IERR) 
                CALL MPI_BCAST(DISNFPARCEL,NNODE,MPI_REAL,0,& 
     &            MPI_COMM_WORLD,MPI_IERR) 
                IF(RANK.EQ.NRANK)THEN 
                DO IN=1,NNODE 
                DISNF_PP(IN,IV,IE_PP)=DISNFPARCEL(IN) 
                ENDDO 
            ENDIF     !LINKS WITH IF STATEMENT ON LINE 85 
 1011 CONTINUE 
 1010 CONTINUE 
! 
! *** CLOSE RESTART FILE 
! 
         IF(RANK.EQ.0)CLOSE(11) 
! 
         ELSE 
! 
! *** INITIAL CONDITIONS FOR A GAS EXPANSION PROBLEM: 
! 
! *** ASK THE USER FOR THE PRE-EXPANSION GAS CONDITIONS: 
! 
       IF(RANK.EQ.0)THEN 
! 
      T1 = IVD%T1 
      P1 = IVD%P1 
      W = IVD%W 
      WRITE(*,*) 
! 
       L=(W*1E-09)/2 
! 
! *** CALCULATE GAS PROPERTIES USED FOR MAXWELL DISTRIBUTION 
!     
      RHO1=(P1*(10**05))/(GC*T1)     !DENSITIES 
      n1=RHO1*NA/M                   !NUMBER DENSITIES 
      TMP1=RHO1/(2*P1*(10**05)) 
      BETA1=SQRT(TMP1)               !BETA VARIABLE 
      ENDIF                          !LINKS TO IF STATEMENT ON LINE 117 
! 
! *** BROADCAST VARIABLES 
! 
      CALL MPI_BCAST(L,1,MPI_REAL,0,MPI_COMM_WORLD,MPI_IERR) 
      CALL MPI_BCAST(BETA1,1,MPI_REAL,0,MPI_COMM_WORLD,MPI_IERR) 
      CALL MPI_BCAST(n1,1,MPI_REAL,0,MPI_COMM_WORLD,MPI_IERR)
! 
! *** BEGIN LOOP OVER THE PHYSICAL SPACE DISCONTINUOUS NODES 
!
       IF(RANK.NE.0)THEN 
       DO 1005 IE=1,NELEM_PP
       DO 1006 IN=1,NNODE 
        IP_PP=INTMA_PP(IN,IE) 
! 
! *** X-COORDINATE OF NODE 
! 
        XPOS=COORD_PP(1,IP_PP)
! 
! *** INSIDE THE GAS CLOUD 
! 
        MAGX=ABS(XPOS)
       IF(MAGX.LE.L)THEN
! 
! *** LOOP OVER ALL VELOCITY SPACE NODES 
! 
       C=(BETA1**2)/(PI)         !COEFFICIENT OF THE MAXWELL DISTRIBUTION FUNCTION
       DO 1002 INV=1,VNPNT
            ETA=VCORD(1,INV) 
            ZETA=VCORD(2,INV) 
! *** HERE WE TRANSFORM THE (ETA,ZETA) COORDINATES BACK TO (CX,CY) COORDINATES 
            R=ETA*(rv/2)+(rv/2)     !FIRST TO POLAR COORDINATES 
            THETA=ZETA*PI 
            UX=R*COS(THETA)          !THEN TO CARTESIANS 
            UY=R*SIN(THETA) 
            TMP=UX*UX+UY*UY         
            SPEED=SQRT(TMP)  !MOLECULAR SPEED AT THIS COORDINATE IN VELSPACE MESH 
            TMP=-((BETA1**2)*(SPEED**2)) 
            F0=C*EXP(TMP)       !DISTRIBUTION FUNCTION 
            DISNF_PP(IN,INV,IE)=n1*F0     !INITIAL CONDITION (nf) MATRIX 
! 
! *** END LOOP OVER VELOCITY SPACE NODES 
! 
 1002 CONTINUE
! 
! *** IF OUTSIDE THE GAS CLOUD, SET nf TO ZERO 
! 
       ELSE
       DO 1003 INV=1,VNPNT 
            DISNF_PP(IN,INV,IE)=0.0
 1003 CONTINUE
      ENDIF 
! 
! *** END LOOP OVER THE PHYSICAL SPACE DISCONTINUOUS NODES 
! 
 1006 CONTINUE
 1005 CONTINUE
!
      ENDIF     !LINKS WITH IF STATEMENT ON LINE 128
! 
! *** SYNCHRONISE THE PROCESSORS 
! 
!	  CALL MPI_BARRIER(MPI_COMM_WORLD) 
! 
       ENDIF
! 
! *** FORMAT STATEMENTS 
! 
 201  FORMAT('WHAT IS THE TEMPERATURE(IN K) OF THE GAS?', $) 
 202  FORMAT('WHAT IS THE PRESSURE (IN bar) OF THE GAS?', $) 
 203  FORMAT('WHAT IS THE WIDTH OF THE GAS CLOUD (in nanometers) ?', $) 
 204  FORMAT('DO WISH TO START THE RUN USING A RESTART FILE? ') 
 205  FORMAT('(YES = 1, NO = 0)',$) 
 206  FORMAT('WHAT IS THE NAME OF THE RESTART FILE?  ',$) 
 208  FORMAT('THIS RESTART FILE IS NOT COMPATIBLE WITH YOUR MESHES!') 
 209  FORMAT('PROGRAM STOPPED') 
! 
      RETURN 
      END 
