      SUBROUTINE MACROS(rv,VNPNT,SUMWEIGHT,NPOIN,NNODE,& 
     &           DISNF,VCORD,INTMA,NELEM,GEOME,NGEOM,& 
     &           ND,RHO,UVEL,VVEL,PS,TEMP,RANK,DISND,DISUX,&
     &           DISUY,DISPS,M,R)
! 
! *** SUBROUTINE CALCULATES MACROSCOPIC PROPERTIES FROM THE DISTRIBUTION 
! *** FUNCTION 
! 
      IMPLICIT NONE 
      INCLUDE 'mpif.h'
! 
      INTEGER VNPNT,NPOIN,NNODE,NELEM,NGEOM 
      INTEGER IN,IV,IP,IE,RANK,MPI_IERR 
      INTEGER INTMA(NNODE,NELEM),TMP 
      REAL rv,R,AE,RT,PI,JAC,ETA,ZETA,N 
      REAL INT,WEIGHT,THETA,BETA,M,MM 
      REAL ND(NPOIN),VCORD(3,VNPNT) 
      REAL INTU,INTV,DENS,NDTMP 
      REAL RHO(NPOIN),UVEL(NPOIN),VVEL(NPOIN)
      REAL TEMP(NPOIN),PS(NPOIN),FLAG(NPOIN)
      REAL CX,CY,CXDASH,CYDASH,INTP,SUMWEIGHT,C4,FRAC
      REAL DISNF(NNODE,VNPNT,NELEM),GEOME(NGEOM,NELEM)
      REAL DISND(NNODE,NELEM),DISUX(NNODE,NELEM),DISUY(NNODE,NELEM)
      REAL DISPS(NNODE,NELEM)
! 
! *** MOLECULAR MASS OF O2 AND GAS CONSTANT 
! 
      PARAMETER(PI=3.1416,C4=4.0) 
!
! *** COMPUTE THE WEIGHTING FACTOR FOR THE FULL V-SPACE QUADRATURE
!
      FRAC=C4/SUMWEIGHT
!
! *** COMPUTE THE MOLECULAR MASS
!
      MM = M/6.022E26
! 
! *** INITIALISE ND(NPOIN),RHO(NPOIN),UVEL(NPOIN),VVEL(NPOIN),TEMP(NPOINT),PS(NPOIN) 
! 
      CALL RFILLV(RHO,NPOIN,0.0) 
      CALL RFILLV(UVEL,NPOIN,0.0)
      CALL RFILLV(VVEL,NPOIN,0.0) 
      CALL RFILLV(TEMP,NPOIN,0.0) 
      CALL RFILLV(PS,NPOIN,0.0) 
      CALL RFILLV(ND,NPOIN,0.0) 
      CALL RFILLV(FLAG,NPOIN,0.0)
!
! *** INITIALISE THE DISCONTINUOUS BULK VARIABLE ARRAYS
!
      CALL RFILLM(DISND,NNODE,NELEM,0.0)
      CALL RFILLM(DISUX,NNODE,NELEM,0.0)
      CALL RFILLM(DISUY,NNODE,NELEM,0.0)
      CALL RFILLM(DISPS,NNODE,NELEM,0.0)
! 
! *** LOOP OVER EACH DISCONTINUOUS NODE IN PHYSICAL SPACE 
! 
      DO 1000 IE=1,NELEM
        AE=GEOME(7,IE) 
        DO 1001 IN=1,NNODE 
          IP=INTMA(IN,IE) 
          FLAG(IP)=FLAG(IP)+AE 
! 
! *** LOOP OVER ALL VSPACE NODES TO CALCULATE NUMBER DENSITY & BULK VELOCITIES 
!	 
          INT=0.0 
          INTU=0.0 
          INTV=0.0 
          DO 2000 IV=1,VNPNT
            ETA=VCORD(1,IV) 
            ZETA=VCORD(2,IV) 
            RT=ETA*(rv/2)+(rv/2)!MAP BACK TO POLAR COORDINATES 
            THETA=ZETA*PI
            CX=RT*COS(THETA)!CONVERT TO CARTESIANS 
            CY=RT*SIN(THETA) 
            WEIGHT=VCORD(3,IV)
            JAC=PI*rv*rv*0.25*(ETA+1)!CALCULATE THE JACOBIAN OF THE TRANSFORMATION 
            INT=INT+DISNF(IN,IV,IE)*WEIGHT*JAC*FRAC
            INTU=INTU+CX*DISNF(IN,IV,IE)*WEIGHT*JAC*FRAC
            INTV=INTV+CY*DISNF(IN,IV,IE)*WEIGHT*JAC*FRAC
 2000 CONTINUE 
          ND(IP)=ND(IP)+INT*AE
          NDTMP=INT
          IF(INT.LT.1e-20)GOTO 2010
            UVEL(IP)=UVEL(IP)+AE*INTU/INT 
            VVEL(IP)=VVEL(IP)+AE*INTV/INT
! ***  STORE THE DISCONTINUOUS ND & VELOCITIES TO BE USED IN CONSTRUCTING THE EQUILIBRIUM
! ***  ND FOR THE BGK RHS
            DISND(IN,IE)=INT
            DISUX(IN,IE)=INTU/INT
            DISUY(IN,IE)=INTV/INT
 2010 CONTINUE
! 
! *** LOOP OVER VSPACE NODES TO CALCULATE STATIC PRESSURE 
! 
        INTP=0.0 
        DO 3000 IV=1,VNPNT 
          ETA=VCORD(1,IV) 
          ZETA=VCORD(2,IV)
          WEIGHT=VCORD(3,IV) 
          RT=ETA*(rv/2)+(rv/2)!MAP BACK TO POLAR COORDINATES 
          THETA=ZETA*PI 
          CX=RT*COS(THETA)!CONVERT TO CARTESIANS 
          CY=RT*SIN(THETA)
          JAC=PI*rv*rv*0.25*(ETA+1)
 !       CXDASH=CX-UVEL(IP) 
 !       CYDASH=CY-VVEL(IP)
          CXDASH=CX-DISUX(IN,IE)
          CYDASH=CY-DISUY(IN,IE) 
          TMP=0.5*(CXDASH*CXDASH+CYDASH*CYDASH) 
          INTP=INTP+TMP*DISNF(IN,IV,IE)*WEIGHT*JAC*FRAC
 3000 CONTINUE 
          PS(IP)=PS(IP)+MM*INTP*AE
 !      DISPS(IN,IE)=INTP*MM-0.5*DISND(IN,IE)*MM*(DISUX(IN,IE)*DISUX(IN,IE)+DISUY(IN,IE)*DISUY(IN,IE))
          DISPS(IN,IE)=INTP*MM
! 
! *** END PHYSICAL SPACE LOOP 
! 
 1001 CONTINUE 
 1000 CONTINUE 
!IF(RANK.EQ.3)THEN
!PRINT*,'DISUX(1,665)=',DISUX(1,665)
!PRINT*,'DISUY(1,665)=',DISUY(1,665)
!PRINT*,'DISPS(1,665)=',DISPS(1,665)
!ENDIF
! 
! *** NORMALISE THE MACRO VARIABLES 
! 
        DO 5000 IP=1,NPOIN 
         IF(ND(IP).LT.1e-20)THEN	!TO AVOID THE 'DIVIDE BY ZERO' 
          RHO(IP)=0.0
          UVEL(IP)=0.0
          VVEL(IP)=0.0
          PS(IP)=0.0
          TEMP(IP)=0.0 
         ELSE
          ND(IP)=ND(IP)/FLAG(IP) 
          RHO(IP)=ND(IP)*MM 
          UVEL(IP)=UVEL(IP)/FLAG(IP) 
          VVEL(IP)=VVEL(IP)/FLAG(IP) 
 !       PS(IP)=(PS(IP)/FLAG(IP))-0.5*RHO(IP)*(UVEL(IP)*UVEL(IP)+VVEL(IP)*VVEL(IP)) 
          PS(IP)=PS(IP)/FLAG(IP)
          TEMP(IP)=PS(IP)/(R*RHO(IP)) 
        ENDIF 
 5000 CONTINUE
! 
      RETURN 
      END 
