SUBROUTINE VSPACE(RORDER, TORDER, VNPNT, VCORD, SUMWEIGHT)
  IMPLICIT NONE
!
! *** THIS ROUTINE READS IN THE LOBATTO WEIGHTING USED FOR VSPACE
! *** INTEGRATION AND CONSTRUCTS THE ETA AND ZETA WEIGHTINGS/COORDINATES
!
  INTEGER RORDER, TORDER, I, VNPNT, IETA, IZETA
!
  REAL ETAWEIGHT(RORDER), ZETAWEIGHT(TORDER)
  REAL ETACHORD(RORDER), ZETACHORD(TORDER)
  REAL WEIGHTING(2, RORDER), VCORD(3, VNPNT)
  REAL GAP, SUMWEIGHT
!
! *** READ IN THE WEIGHTINGS
!
  DO I = 1, RORDER
    READ (10, *) WEIGHTING(1, I), WEIGHTING(2, I)
  ENDDO
!
! *** CONSTRUCT THE ETA AND ZETA WEIGHTINGS
!
  DO I = 1, RORDER
    ETACHORD(I) = WEIGHTING(1, I)
    ETAWEIGHT(I) = WEIGHTING(2, I)
  ENDDO
!
  GAP = 2.0/REAL(TORDER)
  DO I = 1, TORDER
    ZETACHORD(I) = -1 + I*GAP
    ZETAWEIGHT(I) = 1.0
  ENDDO
!
! *** CLOSE THE CHANNELS
!
  CLOSE (10)
!
! *** CONSTRUCT THE VSPACE COORDINATE MATRICES
!
  I = 0
  SUMWEIGHT = 0.0
  DO IETA = 1, RORDER
    DO IZETA = 1, TORDER
      I = I + 1
      VCORD(1, I) = ETACHORD(IETA)
      VCORD(2, I) = ZETACHORD(IZETA)
      VCORD(3, I) = ETAWEIGHT(IETA)*ZETAWEIGHT(IZETA)
      SUMWEIGHT = SUMWEIGHT + VCORD(3, I)
    ENDDO
  ENDDO
  PRINT *, 'SUMWEIGHT=', SUMWEIGHT
!
  RETURN
END
